format_version: v1.0
type: UniqueComponent
attributes: {id: twihs2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '400000'}
  - type: Integer
    attributes: {id: I2C_CLOCK_SPEED_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs2, value: '400000'}
  - type: Integer
    attributes: {id: TWIHS_CLK_SRC_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs2, value: '150000000'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CHDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs2, value: '177'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CKDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs2, value: '0'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CLDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs2, value: '192'}
  - type: Integer
    attributes: {id: TWIHS_TIMEOUT_COUNT_VAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs2, value: '60000'}
- type: ElementPosition
  attributes: {x: '960', y: '20', id: twihs2}
